### PR TITLE
Get It Dan™ Version 1.0

### PR DESCRIPTION
**Pull request by pfaraee**
-Merged commits
-App is now in its most basic form. (Could be considered "done")

### CODE REVIEW

**Comment by moisesbaez** [comment]
I'm getting a null pointer as you can see in the picture below. I traced it with the debugger. Apparently the variable "is" is null even after the try-catch block. Which means that it probably didn't open the file, even though it is there. Is it working on your end?

null-pointer

**Comment by pfaraee** [comment]
Moises I looked it up and the reason everything I was trying wasn't working
is because it is impossible to write to the assets folder. I'll figure out
what to do.

**Comment by moisesbaez** [comment]
I think an alternative would be to first create the file that you want to read, fill it up with the sample JSON data, then try reading it into your app. This is so that you can test the various situations that will occur during normal use (saving the tasks to a file, reading the tasks from the file). You might want to take a look at the following link. It shows you how to first create the file using FileOutputStream, write out the object to the newly created file, then read the object from the file back in.

http://www.vogella.com/tutorials/JavaSerialization/article.html

**Comment by pfaraee** [comment]
I used something similar to that except it was about JSON Serialization in
android.
I just fixed it, and tested it to make sure it should work for you.
What I did was created a function that takes a pre-made json file in the
assets folder, with a single object that serves as a makeshift welcome
message.
As soon as the app is run it writes the data from the assets folder to a
new file in the outputstream. This function is only called once, the first
time you open the app after you install it.

**Pull request merged**
